FROM arm32v7/python:3.6-stretch

LABEL maintainer="matthewgleich@gmail.com"
LABEL description="Image with everything you need to control the sense hat"

# Install:
RUN apt -yq update
RUN apt install -yq sense-hat