FROM raspbian/jessie

LABEL maintainer="matthewgleich@gmail.com"
LABEL description="Image with everything you need to control the sense hat"

# Install:
RUN apt -yq update
RUN apt install -yq python3
RUN apt install -yq sense-hat
