# This is an image that comes with python3 installed and docker installed
# Image is registered under the MIT license
# The mainatainer for this image is Matthew Gleich (Matt-Gleich)

FROM docker:stable

# Metadata
LABEL mainatainer "matthewgleich@gmail.com"
LABEL description "Image that comes with Python3 and Docker installed"

# Installing Python and Pip
RUN apk add --no-cache python3.6

CMD ["python3"]
